image: wpilib/roborio-cross-ubuntu:2020-18.04

tasks:
  - init: ./gradlew build

vscode:
  extensions:
    - wpilibsuite.vscode-wpilib@2020.3.2:RAxZwFw1Ra3mIl+oIDddXg==
    - shengchen.vscode-checkstyle@1.3.3:OLnTgzZgg9XCXrKjyHLdhA==
    - gregk.botbuilder@0.5.0:eCjkhsYRzVG7448fdaEVbg==